### ISSUE TITLE
[BUG] LUNC dollar value wrong on main screen

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1429] opened 2024-11-30 19:27 UTC
**Describe the bug**
The dollar value of LUNA Classic is displayed wrongly on main screen. But on detail screen it is displayed correctly.

**Expected behavior**
Display correctly

**Screenshots**
![Image](https://github.com/user-attachments/assets/94220955-f127-4a23-b0b1-bde4212bd3d3)
![Image](https://github.com/user-attachments/assets/69dda9c4-43ab-46c8-9f7f-4f47e97b8b10)

 - Version 34

**Additional context**
https://discord.com/channels/1203844257220395078/1300035020232196196/1312323903162417152

**Comment by aminsato** [comment] 2024-12-02 05:51
@realpaaao 
Unable to reproduce the issue. For further investigation, I need the address causing the problem.
https://github.com/user-attachments/assets/da7418e1-97d7-4349-8856-f59ac0f99e3f

**Comment by johnnyluo** [comment] 2024-12-04 22:17
closing , since we are not able to reproduce it

**Closed by johnnyluo** 2024-12-04 22:17 UTC
Labels: bug :lady_beetle:
