### ISSUE TITLE
[BUG] Swapping between EVM chains that are not available

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#1137] opened 2024-10-10 09:30 UTC
**Describe the bug**
When changing swap routes to swaps between EVM chains and tokens, the page does not get updated and able to proceed with the last viable sawp

**To Reproduce**
1. Go to `swap`
2. Click on a available swap
3. schange to swap between EVM that is not available
4. See error and able to proceed swapping

**Expected behavior**
Display errors when a route is not available and block the progress

**Screenshots**

 - Version 27

**Comment by johnnyluo** [comment] 2024-10-20 23:01
closing , duplicate of 1174, in favor of #1174

**Closed by johnnyluo** 2024-10-20 23:01 UTC
Labels: bug :lady_beetle:
