### ISSUE TITLE
BUG: FAQs missing answers

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-android#220] opened 2024-05-26 00:24 UTC
BUG: FAQ dropdowns can't be opened.

Desired: Please add dropdown answers from [FAQ](https://vultisig.com/faq.html)

![image](https://github.com/vultisig/vultisig-android/assets/167348323/555b57d8-9384-4a7e-b6da-e4b975dbdfc6)

**Comment by YGolybev** [comment] 2024-05-27 04:21
Duplicate of #167 @aminsato

**Closed** 2024-05-28 15:56 UTC
Labels: bug
